### ISSUE TITLE
Update for newer biblatex version

### ISSUE THREAD

**Issue by Chickenmarkus** [gvdgdo/biblatex-lncs#3]
Hi,

unfortunately there is still now LNCS template for biblatex offered by Springer. However, in the meanwhile your great template is outdated because biblatex has changed the name format (http://tex.stackexchange.com/questions/299036/biblatex-3-3-name-formatting). This is in conflict with line 106 and 113 of your `line.bbx`.

An updated version of your template would be very welcome.

Best,
Markus

**Comment by rriemann** [comment]
I ran into the same issue. The error message is:

```
./lncs.bbx:106: Illegal parameter number in definition of \\blx@defformat@d.<to be read again> 
                   5                                                                                                                                            
l.106   \\ifblank{#5                                                                                                                                            
                   }{}{#5\\space##1, ##4}%                                                                                                                      
You meant to type ## instead of #, right?                                                                                                                       
Or maybe a } was forgotten somewhere earlier, and things                                                                                                        
are all screwed up? I'm going to assume that you meant ##.   
```

**Comment by gvdgdo** [comment]
It is easy to fix. it is due to the new biblatex specifications for names. I can work on it next week,

**Comment by rriemann** [comment]
I have a paper to submit very soon. I tried to do it on my own, but failed. :(

**Comment by rriemann** [comment]
Off-topic: Maybe you could also update the bbx from here (which works better for me): https://github.com/neapel/biblatex-lncs/blob/master/lncs.bbx

**Comment by gvdgdo** [comment]
accepted pull request to fix the issues with the new name format
